name: AMI build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create and configure
        run: |
          touch .env
          echo pd=${{ secrets.PASSWORD }}>> .env
          echo database=${{ secrets.DATABASE }} >> .env
          echo user=${{ secrets.USER }} >> .env

      - name: Zipping all files
        run: zip -r webapp.zip .

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
          unzip -j packer_1.7.2_linux_amd64.zip -d /tmp
          chmod +x /tmp/packer
          sudo mv /tmp/packer /usr/local/bin/
          packer version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Packer Intialization
        run : packer init .

      - name: Check build of packer
        run: packer build -var 'MY_PASSWORD=${{ secrets.PASSWORD }}' -var 'MY_DATABASE=${{ secrets.DATABASE }}' -var 'MY_USER=${{ secrets.USER }}' -var-file="variables.pkrvars.hcl" aws-ami.pkr.hcl

      - name: Getting the latest AMI ID
        run: |
          echo AMI_ID=$(jq -r '.builds[-1].artifact_id' ./manifest.json | cut -d ":" -f2) >> $GITHUB_ENV
        shell: bash

      - name: Creating a new version of the Launch Template
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEMO_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEMO_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ec2 create-launch-template-version --launch-template-name ec2LT --source-version 1 --launch-template-data '{"ImageId":"${{ env.AMI_ID }}"}'
          echo "Launch template ID completed"

      - name: Instance Refresh for auto scale using the new Launch Template
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEMO_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEMO_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          INSTANCE_REFRESH_ID=$(aws autoscaling start-instance-refresh --auto-scaling-group-name auto-scaling-group --query 'InstanceRefreshId' --output text)
          echo "Instance refresh for Launch template ID in AS started with ID: ${INSTANCE_REFRESH_ID}"

          # Wait for the instance refresh to complete
          while true; do
            STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name auto-scaling-group --instance-refresh-ids ${INSTANCE_REFRESH_ID} --query 'InstanceRefreshes[0].Status' --output text)
            if [ "$STATUS" == "Successful" ]; then
              echo "Instance refresh for Launch template ID in AS completed successfully."
              break
            elif [ "$STATUS" == "Cancelled" ]; then
              echo "Instance refresh for Launch template ID in AS failed."
              exit 1
            elif [ "$STATUS" == "Failed" ]; then
              echo "Instance refresh for Launch template ID in AS failed."
              exit 1
            else
              echo "Waiting for instance refresh to complete. Current status: $STATUS"
              sleep 60  # Adjust the sleep interval as needed
            fi
          done
#