name: Webapp-CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DATABASE }}
          MYSQL_ROOT_HOST: "%"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: create and configure
        run: |
            touch .env
            echo port=${{ secrets.PORT }} >> .env
            echo DB_HOST=${{ secrets.HOST }} >> .env
            echo DB_DIALECT=${{ secrets.DIALECT }} >> .env
            echo DB_USER=${{ secrets.USER }} >> .env
            echo DB_PASSWORD=${{ secrets.PASSWORD }}>> .env
            echo DB_NAME=${{ secrets.DATABASE }} >> .env

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: nohup npm start & npm test
