# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          host-port: 3306 # Optional, default value is 3306. The port of the host
          container-port: 3306 # Optional, default value is 3306. The port of the container
          mariadb-version: '10.4.10' # Optional, default value is "latest". The version of MariaDB
          mysql-database: 'Cloud' # Optional, default value is "test". The specified database to be created
          mysql-user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets too
          mysql-password: 'shahdeep'

      - name: Install dependencies
        run: npm install

      - name: Start Node.js app
        run: npm start
            
      - name: Test the server
        run: |
          npm test
